"""Add WAVE features: leaderboard, copy trading, referral

Revision ID: ece66fe4d11d
Revises: f70a5526ace1
Create Date: 2025-10-27 01:06:58.722196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'ece66fe4d11d'
down_revision: Union[str, None] = 'f70a5526ace1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referral_campaigns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('campaign_code', sa.String(), nullable=True),
    sa.Column('bonus_referrer_discount', sa.Float(), nullable=True),
    sa.Column('bonus_referred_discount', sa.Float(), nullable=True),
    sa.Column('bonus_referrer_share', sa.Float(), nullable=True),
    sa.Column('min_trades_required', sa.Integer(), nullable=True),
    sa.Column('min_volume_required', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('total_participants', sa.Integer(), nullable=True),
    sa.Column('total_conversions', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_code')
    )
    op.create_index('idx_campaign_active', 'referral_campaigns', ['is_active', 'start_date', 'end_date'], unique=False)
    op.create_index('idx_campaign_code', 'referral_campaigns', ['campaign_code'], unique=False)
    op.create_table('copy_relationships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('follower_id', sa.String(), nullable=False),
    sa.Column('leader_id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=True),
    sa.Column('copy_ratio', sa.Float(), nullable=False),
    sa.Column('max_position_size', sa.Float(), nullable=True),
    sa.Column('min_position_size', sa.Float(), nullable=True),
    sa.Column('stop_loss_multiplier', sa.Float(), nullable=True),
    sa.Column('take_profit_multiplier', sa.Float(), nullable=True),
    sa.Column('max_daily_loss', sa.Float(), nullable=True),
    sa.Column('max_daily_trades', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('auto_start', sa.Boolean(), nullable=True),
    sa.Column('copy_close_only', sa.Boolean(), nullable=True),
    sa.Column('profit_share_percentage', sa.Float(), nullable=True),
    sa.Column('total_shared_profit', sa.Float(), nullable=True),
    sa.Column('pending_payout', sa.Float(), nullable=True),
    sa.Column('total_copied_trades', sa.Integer(), nullable=True),
    sa.Column('successful_copies', sa.Integer(), nullable=True),
    sa.Column('failed_copies', sa.Integer(), nullable=True),
    sa.Column('total_pnl', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_copied_at', sa.DateTime(), nullable=True),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['leader_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_copy_follower_active', 'copy_relationships', ['follower_id', 'is_active'], unique=False)
    op.create_index('idx_copy_leader_active', 'copy_relationships', ['leader_id', 'is_active'], unique=False)
    op.create_index('idx_copy_relationship', 'copy_relationships', ['follower_id', 'leader_id'], unique=False)
    op.create_table('referral_codes',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_referral_code_active', 'referral_codes', ['is_active'], unique=False)
    op.create_index('idx_referral_code_user', 'referral_codes', ['user_id'], unique=False)
    op.create_table('copied_trades',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('copy_relationship_id', sa.String(), nullable=False),
    sa.Column('leader_trade_id', sa.String(), nullable=True),
    sa.Column('follower_trade_id', sa.String(), nullable=True),
    sa.Column('leader_order_id', sa.String(), nullable=True),
    sa.Column('follower_order_id', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=True),
    sa.Column('leader_quantity', sa.Float(), nullable=False),
    sa.Column('follower_quantity', sa.Float(), nullable=False),
    sa.Column('leader_entry_price', sa.Float(), nullable=True),
    sa.Column('follower_entry_price', sa.Float(), nullable=True),
    sa.Column('copy_ratio_used', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('slippage', sa.Float(), nullable=True),
    sa.Column('follower_pnl', sa.Float(), nullable=True),
    sa.Column('profit_shared', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('leader_order_time', sa.DateTime(), nullable=True),
    sa.Column('follower_order_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['copy_relationship_id'], ['copy_relationships.id'], ),
    sa.ForeignKeyConstraint(['follower_trade_id'], ['trades.id'], ),
    sa.ForeignKeyConstraint(['leader_trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_copied_follower_trade', 'copied_trades', ['follower_trade_id'], unique=False)
    op.create_index('idx_copied_leader_trade', 'copied_trades', ['leader_trade_id'], unique=False)
    op.create_index('idx_copied_relationship_time', 'copied_trades', ['copy_relationship_id', 'created_at'], unique=False)
    op.create_index('idx_copied_status', 'copied_trades', ['status'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('referrer_id', sa.String(), nullable=False),
    sa.Column('referred_id', sa.String(), nullable=False),
    sa.Column('referral_code', sa.String(), nullable=False),
    sa.Column('referrer_discount_earned', sa.Float(), nullable=True),
    sa.Column('referred_discount_earned', sa.Float(), nullable=True),
    sa.Column('referrer_share_earned', sa.Float(), nullable=True),
    sa.Column('referrer_discount_percentage', sa.Float(), nullable=True),
    sa.Column('referred_discount_percentage', sa.Float(), nullable=True),
    sa.Column('referrer_share_percentage', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('first_trade_at', sa.DateTime(), nullable=True),
    sa.Column('milestone_trades_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referral_code'], ['referral_codes.code'], ),
    sa.ForeignKeyConstraint(['referred_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referred_id')
    )
    op.create_index('idx_referral_code', 'referrals', ['referral_code'], unique=False)
    op.create_index('idx_referral_referred', 'referrals', ['referred_id'], unique=False)
    op.create_index('idx_referral_referrer', 'referrals', ['referrer_id'], unique=False)
    op.create_index('idx_referral_status', 'referrals', ['status', 'is_active'], unique=False)
    op.drop_table('trading_configs')
    op.drop_table('telegram_configs')
    op.drop_column('users', 'badges')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('badges', sqlite.JSON(), nullable=True))
    op.create_table('telegram_configs',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('bot_token', sa.VARCHAR(), nullable=False),
    sa.Column('chat_id', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('notify_entry', sa.BOOLEAN(), nullable=True),
    sa.Column('notify_exit', sa.BOOLEAN(), nullable=True),
    sa.Column('notify_stop_loss', sa.BOOLEAN(), nullable=True),
    sa.Column('notify_take_profit', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('trading_configs',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('api_key_id', sa.VARCHAR(), nullable=False),
    sa.Column('strategy', sa.VARCHAR(), nullable=True),
    sa.Column('investment_type', sa.VARCHAR(length=10), nullable=True),
    sa.Column('investment_value', sa.FLOAT(), nullable=False),
    sa.Column('leverage', sa.FLOAT(), nullable=True),
    sa.Column('stop_loss_percentage', sa.FLOAT(), nullable=True),
    sa.Column('take_profit_percentage', sa.FLOAT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('idx_referral_status', table_name='referrals')
    op.drop_index('idx_referral_referrer', table_name='referrals')
    op.drop_index('idx_referral_referred', table_name='referrals')
    op.drop_index('idx_referral_code', table_name='referrals')
    op.drop_table('referrals')
    op.drop_index('idx_copied_status', table_name='copied_trades')
    op.drop_index('idx_copied_relationship_time', table_name='copied_trades')
    op.drop_index('idx_copied_leader_trade', table_name='copied_trades')
    op.drop_index('idx_copied_follower_trade', table_name='copied_trades')
    op.drop_table('copied_trades')
    op.drop_index('idx_referral_code_user', table_name='referral_codes')
    op.drop_index('idx_referral_code_active', table_name='referral_codes')
    op.drop_table('referral_codes')
    op.drop_index('idx_copy_relationship', table_name='copy_relationships')
    op.drop_index('idx_copy_leader_active', table_name='copy_relationships')
    op.drop_index('idx_copy_follower_active', table_name='copy_relationships')
    op.drop_table('copy_relationships')
    op.drop_index('idx_campaign_code', table_name='referral_campaigns')
    op.drop_index('idx_campaign_active', table_name='referral_campaigns')
    op.drop_table('referral_campaigns')
    # ### end Alembic commands ###
