"""Add leaderboard and leaderboard_badges tables

Revision ID: f70a5526ace1
Revises: d6b5c1bb60ba
Create Date: 2025-10-27 00:27:12.016272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f70a5526ace1'
down_revision: Union[str, None] = 'd6b5c1bb60ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaderboard',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('winning_trades', sa.Integer(), nullable=True),
    sa.Column('losing_trades', sa.Integer(), nullable=True),
    sa.Column('total_pnl', sa.Float(), nullable=True),
    sa.Column('total_pnl_percentage', sa.Float(), nullable=True),
    sa.Column('roi', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('avg_win', sa.Float(), nullable=True),
    sa.Column('avg_loss', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('previous_rank', sa.Integer(), nullable=True),
    sa.Column('rank_change', sa.Integer(), nullable=True),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('allow_copy', sa.Boolean(), nullable=True),
    sa.Column('copy_count', sa.Integer(), nullable=True),
    sa.Column('last_trade_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_leaderboard_period_rank', 'leaderboard', ['period', 'rank'], unique=False)
    op.create_index('idx_leaderboard_public', 'leaderboard', ['is_public', 'period'], unique=False)
    op.create_index('idx_leaderboard_roi', 'leaderboard', ['roi'], unique=False)
    op.create_index('idx_leaderboard_user_period', 'leaderboard', ['user_id', 'period'], unique=False)
    op.create_index('idx_leaderboard_win_rate', 'leaderboard', ['win_rate'], unique=False)
    op.create_table('leaderboard_badges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('badge_type', sa.String(), nullable=False),
    sa.Column('badge_name', sa.String(), nullable=False),
    sa.Column('badge_description', sa.String(), nullable=True),
    sa.Column('badge_icon', sa.String(), nullable=True),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('achieved_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('badge_metadata', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trading_configs',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('api_key_id', sa.VARCHAR(), nullable=False),
    sa.Column('strategy', sa.VARCHAR(), nullable=True),
    sa.Column('investment_type', sa.VARCHAR(length=10), nullable=True),
    sa.Column('investment_value', sa.FLOAT(), nullable=False),
    sa.Column('leverage', sa.FLOAT(), nullable=True),
    sa.Column('stop_loss_percentage', sa.FLOAT(), nullable=True),
    sa.Column('take_profit_percentage', sa.FLOAT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telegram_configs',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('bot_token', sa.VARCHAR(), nullable=False),
    sa.Column('chat_id', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('notify_entry', sa.BOOLEAN(), nullable=True),
    sa.Column('notify_exit', sa.BOOLEAN(), nullable=True),
    sa.Column('notify_stop_loss', sa.BOOLEAN(), nullable=True),
    sa.Column('notify_take_profit', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_table('leaderboard_badges')
    op.drop_index('idx_leaderboard_win_rate', table_name='leaderboard')
    op.drop_index('idx_leaderboard_user_period', table_name='leaderboard')
    op.drop_index('idx_leaderboard_roi', table_name='leaderboard')
    op.drop_index('idx_leaderboard_public', table_name='leaderboard')
    op.drop_index('idx_leaderboard_period_rank', table_name='leaderboard')
    op.drop_table('leaderboard')
    # ### end Alembic commands ###
