global:
  resolve_timeout: 5m
  slack_api_url: '${SLACK_WEBHOOK_URL}'
  smtp_from: 'alerts@trendy.storydot.kr'
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_auth_username: '${SMTP_USERNAME}'
  smtp_auth_password: '${SMTP_PASSWORD}'

# Templates for alert notifications
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Route alerts to different receivers based on labels
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default'

  routes:
    # Critical alerts go to multiple channels
    - match:
        severity: critical
      receiver: 'critical-alerts'
      continue: true

    # Trading-specific alerts
    - match:
        component: trading
      receiver: 'trading-team'
      continue: true

    # Backend/Frontend alerts
    - match_re:
        component: backend|frontend
      receiver: 'dev-team'

    # Database alerts
    - match:
        component: database
      receiver: 'ops-team'

    # Business metrics alerts
    - match:
        component: business
      receiver: 'business-team'

# Alert receivers configuration
receivers:
  - name: 'default'
    slack_configs:
      - channel: '#trading-alerts'
        title: '{{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}\n{{ .Annotations.description }}{{ end }}'

  - name: 'critical-alerts'
    slack_configs:
      - channel: '#critical-alerts'
        title: '🚨 CRITICAL: {{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}\n{{ .Annotations.description }}{{ end }}'
        send_resolved: true

    pagerduty_configs:
      - service_key: '${PAGERDUTY_SERVICE_KEY}'
        description: '{{ .GroupLabels.alertname }}: {{ .Annotations.summary }}'

    telegram_configs:
      - bot_token: '${TELEGRAM_BOT_TOKEN}'
        chat_id: ${TELEGRAM_CHAT_ID}
        message: |
          🚨 *CRITICAL ALERT*

          *Alert:* {{ .GroupLabels.alertname }}
          *Severity:* {{ .CommonLabels.severity }}
          *Component:* {{ .CommonLabels.component }}

          {{ range .Alerts }}
          *Summary:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Started:* {{ .StartsAt }}
          {{ end }}
        parse_mode: 'Markdown'

    email_configs:
      - to: 'ops@trendy.storydot.kr'
        subject: '🚨 CRITICAL: {{ .GroupLabels.alertname }}'
        html: |
          <h2>Critical Alert Triggered</h2>
          <p><strong>Alert:</strong> {{ .GroupLabels.alertname }}</p>
          <p><strong>Severity:</strong> {{ .CommonLabels.severity }}</p>
          <p><strong>Component:</strong> {{ .CommonLabels.component }}</p>

          {{ range .Alerts }}
          <h3>{{ .Annotations.summary }}</h3>
          <p>{{ .Annotations.description }}</p>
          <p><strong>Started:</strong> {{ .StartsAt }}</p>
          {{ end }}

  - name: 'trading-team'
    slack_configs:
      - channel: '#trading-team'
        title: '📊 Trading Alert: {{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}\n{{ .Annotations.description }}{{ end }}'

    telegram_configs:
      - bot_token: '${TELEGRAM_BOT_TOKEN}'
        chat_id: ${TELEGRAM_TRADING_CHAT_ID}
        message: |
          📊 *Trading Alert*

          *Alert:* {{ .GroupLabels.alertname }}
          *Severity:* {{ .CommonLabels.severity }}

          {{ range .Alerts }}
          {{ .Annotations.summary }}
          {{ .Annotations.description }}
          {{ end }}
        parse_mode: 'Markdown'

  - name: 'dev-team'
    slack_configs:
      - channel: '#dev-team'
        title: '🔧 Development Alert: {{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}\n{{ .Annotations.description }}{{ end }}'

  - name: 'ops-team'
    slack_configs:
      - channel: '#ops-team'
        title: '⚙️ Operations Alert: {{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}\n{{ .Annotations.description }}{{ end }}'

    email_configs:
      - to: 'ops@trendy.storydot.kr'
        subject: '⚙️ Ops Alert: {{ .GroupLabels.alertname }}'

  - name: 'business-team'
    slack_configs:
      - channel: '#business-metrics'
        title: '💼 Business Alert: {{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}\n{{ .Annotations.description }}{{ end }}'

    email_configs:
      - to: 'business@trendy.storydot.kr'
        subject: '💼 Business Metrics: {{ .GroupLabels.alertname }}'

# Inhibition rules
inhibit_rules:
  # Inhibit non-critical alerts if critical alert is firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'component']

  # If backend is down, don't alert on API errors
  - source_match:
      alertname: 'BackendDown'
    target_match_re:
      alertname: 'HighErrorRate|SlowAPIResponse'
    equal: ['instance']

  # If database is down, don't alert on connection errors
  - source_match:
      alertname: 'DatabaseDown'
    target_match_re:
      alertname: 'HighDatabaseConnections|SlowDatabaseQueries'
    equal: ['instance']

  # If exchange API is down, don't alert on order failures
  - source_match:
      alertname: 'ExchangeAPIDown'
    target_match:
      alertname: 'HighOrderFailureRate'
    equal: ['exchange']
