groups:
  - name: trading_system
    interval: 30s
    rules:
      # Backend health alerts
      - alert: BackendDown
        expr: up{job="trading-backend"} == 0
        for: 2m
        labels:
          severity: critical
          component: backend
        annotations:
          summary: "Backend service is down"
          description: "Trading backend has been down for more than 2 minutes"

      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
          component: backend
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} (threshold: 5%)"

      - alert: SlowAPIResponse
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
          component: backend
        annotations:
          summary: "API response time is slow"
          description: "95th percentile response time is {{ $value }}s (threshold: 1s)"

      # Trading performance alerts
      - alert: HighOrderFailureRate
        expr: rate(order_failures_total[10m]) / rate(orders_total[10m]) > 0.1
        for: 5m
        labels:
          severity: critical
          component: trading
        annotations:
          summary: "High order failure rate"
          description: "Order failure rate is {{ $value | humanizePercentage }} (threshold: 10%)"

      - alert: ExchangeAPIDown
        expr: exchange_api_up{exchange=~"binance|okx"} == 0
        for: 3m
        labels:
          severity: critical
          component: exchange
        annotations:
          summary: "Exchange API is down"
          description: "{{ $labels.exchange }} API has been unreachable for 3 minutes"

      - alert: WebSocketDisconnected
        expr: websocket_connected == 0
        for: 2m
        labels:
          severity: warning
          component: trading
        annotations:
          summary: "WebSocket connection lost"
          description: "WebSocket for {{ $labels.exchange }} has been disconnected for 2 minutes"

      # Database alerts
      - alert: DatabaseDown
        expr: up{job="postgres"} == 0
        for: 1m
        labels:
          severity: critical
          component: database
        annotations:
          summary: "PostgreSQL is down"
          description: "Database has been unreachable for 1 minute"

      - alert: HighDatabaseConnections
        expr: pg_stat_activity_count > 80
        for: 5m
        labels:
          severity: warning
          component: database
        annotations:
          summary: "High number of database connections"
          description: "Database has {{ $value }} active connections (threshold: 80)"

      - alert: SlowDatabaseQueries
        expr: rate(pg_stat_database_tup_fetched[5m]) / rate(pg_stat_database_tup_returned[5m]) < 0.7
        for: 10m
        labels:
          severity: warning
          component: database
        annotations:
          summary: "Database queries are inefficient"
          description: "Query efficiency is {{ $value | humanizePercentage }}"

      # Cache alerts
      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 2m
        labels:
          severity: warning
          component: cache
        annotations:
          summary: "Redis cache is down"
          description: "Redis has been unreachable for 2 minutes"

      - alert: LowCacheHitRate
        expr: rate(redis_keyspace_hits_total[5m]) / (rate(redis_keyspace_hits_total[5m]) + rate(redis_keyspace_misses_total[5m])) < 0.7
        for: 10m
        labels:
          severity: warning
          component: cache
        annotations:
          summary: "Low cache hit rate"
          description: "Cache hit rate is {{ $value | humanizePercentage }} (threshold: 70%)"

      # System resource alerts
      - alert: HighCPUUsage
        expr: (100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) > 80
        for: 5m
        labels:
          severity: warning
          component: system
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value | humanize }}% on {{ $labels.instance }}"

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
          component: system
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value | humanize }}% on {{ $labels.instance }}"

      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100 < 15
        for: 5m
        labels:
          severity: warning
          component: system
        annotations:
          summary: "Low disk space"
          description: "Only {{ $value | humanize }}% disk space remaining on {{ $labels.instance }}"

      # Business metrics alerts
      - alert: NoTradingActivity
        expr: rate(trades_total[30m]) == 0
        for: 1h
        labels:
          severity: warning
          component: business
        annotations:
          summary: "No trading activity detected"
          description: "No trades executed in the last 30 minutes"

      - alert: HighDrawdown
        expr: portfolio_drawdown_percent > 15
        for: 5m
        labels:
          severity: critical
          component: business
        annotations:
          summary: "High portfolio drawdown"
          description: "Portfolio drawdown is {{ $value }}% (threshold: 15%)"

      - alert: UnusualTradingVolume
        expr: abs(rate(trading_volume_usd[5m]) - avg_over_time(rate(trading_volume_usd[5m])[1h:5m])) / avg_over_time(rate(trading_volume_usd[5m])[1h:5m]) > 2
        for: 10m
        labels:
          severity: warning
          component: business
        annotations:
          summary: "Unusual trading volume detected"
          description: "Trading volume deviated by {{ $value | humanizePercentage }} from 1h average"

  - name: frontend_alerts
    interval: 30s
    rules:
      - alert: FrontendDown
        expr: up{job="trading-frontend"} == 0
        for: 2m
        labels:
          severity: critical
          component: frontend
        annotations:
          summary: "Frontend service is down"
          description: "Trading frontend has been down for more than 2 minutes"

      - alert: HighFrontendErrorRate
        expr: rate(nextjs_errors_total[5m]) > 10
        for: 5m
        labels:
          severity: warning
          component: frontend
        annotations:
          summary: "High frontend error rate"
          description: "Frontend error rate is {{ $value }} errors/sec"

      - alert: SlowPageLoad
        expr: histogram_quantile(0.95, rate(nextjs_page_load_duration_seconds_bucket[5m])) > 3
        for: 5m
        labels:
          severity: warning
          component: frontend
        annotations:
          summary: "Slow page load times"
          description: "95th percentile page load time is {{ $value }}s (threshold: 3s)"
